version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=budget-tracker
    ports:
      - '5432:5432'
